name: tf
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - tensorflow-gpu=2.2.0
  - pandas=1.1.0
  - natsort=7.0.1
  - tqdm=4.48.2
  - tensorflow-probability=0.7.0
  - xarray=0.16.0
  - mne=0.20.7
  - keras=2.4.3
  - ipykernel=5.3.4
  - progressbar2=3.37.1
  - seaborn=0.11.0
  - ipython=7.18.1
  - ipympl=0.5.8
  - pingouin=0.3.8
